### ISSUE TITLE
Issue in ride request widget sdk for android

### ISSUE THREAD

**Issue by Vipulmittal102** [uber/rides-android-sdk#15] opened 2016-04-18 04:58 UTC
Bug relates to ride request widget which has just been introduced by uber.

I am able to book cab,  but when trying to call/message driver I am getting following error:

ERR_UNKNOWN_URL_SCHEME

**Comment by arogal** [comment] 2016-04-18 05:05
Which version of Android are you testing on?

**Comment by Vipulmittal102** [comment] 2016-04-18 05:07
Tested on marshmallow

**Comment by Vipulmittal102** [comment] 2016-04-18 05:52
Should i share code ??

**Comment by arogal** [comment] 2016-04-18 05:55
I think we've identified the issue: http://stackoverflow.com/questions/4338305/android-webview-tel-links-show-web-page-not-found

We'll need to make a slight SDK modification to fix this. We'll keep you posted!

**Comment by Vipulmittal102** [comment] 2016-04-18 06:01
Thanks Arogal for quick response.

Hoping to get this fix as soon as possible.

**Comment by Vipulmittal102** [comment] 2016-04-18 10:30
Just for info,  i tried this solution in a sample app.  Working perfectly

**Comment by itstexter** [comment] 2016-04-18 18:22
Hey @Vipulmittal102!

Trying to get a fix for this out today.  Just letting you know that I edited your original post to remove the screenshot since it had an actual phone number in it.  Will update this thread when the fix is out!  Thank you so much for catching this.

**Comment by itstexter** [comment] 2016-04-18 22:44
This is fixed in release [v0.3.0](https://github.com/uber/rides-android-sdk/releases/tag/v0.3.0).  Thanks again so much for pointing this out!

**Closed by itstexter** 2016-04-18 22:44 UTC

**Comment by Vipulmittal102** [comment] 2016-04-19 03:42
Great!
Thanks for solving this issue.

**Comment by Vipulmittal102** [comment] 2016-04-26 04:24
Hi,

Ride request widget was working perfectly till last night. But today, its
not opening with uber splash screen coming consistently with logo zooming
in and out.

Some users of our app have started complaining already .

We have not updated our app, so there must be some bug on widget itself.
Please look into this

**Comment by itstexter** [comment] 2016-04-26 04:48
Hey @Vipulmittal102,

Thanks so much for catching this.  We've confirmed it and are working on a fix right now!

**Comment by arogal** [comment] 2016-04-26 06:09
This is fixed now @Vipulmittal102. Again, thank you for reporting this.

**Comment by Vipulmittal102** [comment] 2016-04-26 07:26
Great.

That was really quick.

Thanks Adam and Uber team.

**Comment by Vipulmittal102** [comment] 2016-05-10 19:02
Hi,

There seems to be some connectivity issue while performing login through
widget.

Widget is throwing Authentication error due to *connectivity issue.*

Please look into this since this is hampering user experience considerably.


Thanks,
Vipul

**Comment by itstexter** [comment] 2016-05-11 02:59
Hey @Vipulmittal102,

We've confirmed this is occurring for certain apps and are working toward a fix now.

**Comment by arogal** [comment] 2016-05-11 15:11
Hi Vipul. This should be fixed now. Can you confirm please?

**Comment by Vipulmittal102** [comment] 2016-05-11 17:01
Hi Adam,

Its working fine now.
Thanks

**Comment by Vipulmittal102** [comment] 2016-06-09 06:28
Hi Adam,

Greetings for the day.

We are getting consistent feedback of coupon integration and surge/rate
information of uber cabs on widget. Can we have an enhacemnt regarding this
on ride request widget?

Please look into this if its possible.

Thanks

**Comment by arogal** [comment] 2016-06-09 06:31
Can you please file a new issue for this? We'll follow up there.

**Comment by Vipulmittal102** [comment] 2016-06-09 06:43
Hi,

Created the issue.

https://github.com/uber/rides-android-sdk/issues/25.

Thanks

**Comment by j05u3** [comment] 2017-05-26 03:11
Hi,
Widget is throwing Authentication error due to connectivity issue in my app. I am using the 0.6.1 version of the uber skd.
